"""empty message

Revision ID: 13a88dff9b9f
Revises: 3098303fea63
Create Date: 2022-01-16 19:58:52.248390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13a88dff9b9f'
down_revision = '3098303fea63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'bot',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'bot',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
