"""empty message

Revision ID: 14c78836e76d
Revises: 880dfd235937
Create Date: 2022-05-17 22:57:01.460770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c78836e76d'
down_revision = '880dfd235937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channels', 'position',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('channels', 'nsfw',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channels', 'nsfw',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('channels', 'position',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
