"""empty message

Revision ID: 1dbf1d6f2ff5
Revises: 1fee32cbdab2
Create Date: 2022-05-08 18:48:29.762334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dbf1d6f2ff5'
down_revision = '1fee32cbdab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mfa', sa.Column('backup_secret', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mfa', 'backup_secret')
    # ### end Alembic commands ###
