"""empty message

Revision ID: 1f1d30d17df4
Revises: c3481a3298d1
Create Date: 2021-11-18 23:47:40.522001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1d30d17df4'
down_revision = 'c3481a3298d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
