"""empty message

Revision ID: 1fee32cbdab2
Revises: 1483bf14e366
Create Date: 2022-05-08 18:38:35.572779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fee32cbdab2'
down_revision = '1483bf14e366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfa',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=False),
    sa.Column('backup_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_enabled')
    op.drop_table('mfa')
    # ### end Alembic commands ###
