"""empty message

Revision ID: 29a3d6b8dd4a
Revises: e39a29767b9d
Create Date: 2022-05-06 12:44:39.675921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a3d6b8dd4a'
down_revision = 'e39a29767b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('accent_color', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('banner', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banner')
    op.drop_column('users', 'accent_color')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
