"""empty message

Revision ID: 2a8b0838ed1d
Revises: 70537b55f4c5
Create Date: 2021-12-31 11:21:53.150385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a8b0838ed1d'
down_revision = '70537b55f4c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
