"""empty message

Revision ID: 317ddf3a53c7
Revises: 
Create Date: 2022-04-11 23:11:04.492604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317ddf3a53c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
