"""empty message

Revision ID: 34288f90e9dc
Revises: 14c78836e76d
Create Date: 2022-05-18 21:48:39.263331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34288f90e9dc'
down_revision = '14c78836e76d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_members', sa.Column('closed', sa.Boolean(), nullable=False))
    op.drop_constraint('channel_members_user_id_fkey', 'channel_members', type_='foreignkey')
    op.drop_constraint('channel_members_channel_id_fkey', 'channel_members', type_='foreignkey')
    op.create_foreign_key(None, 'channel_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'channel_members', 'channels', ['channel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'channel_members', type_='foreignkey')
    op.drop_constraint(None, 'channel_members', type_='foreignkey')
    op.create_foreign_key('channel_members_channel_id_fkey', 'channel_members', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('channel_members_user_id_fkey', 'channel_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('channel_members', 'closed')
    # ### end Alembic commands ###
