"""empty message

Revision ID: 4290e3aaa29b
Revises: 1dbf1d6f2ff5
Create Date: 2022-05-11 12:59:48.999103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4290e3aaa29b'
down_revision = '1dbf1d6f2ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('icon', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'icon')
    # ### end Alembic commands ###
