"""empty message

Revision ID: 5c0893c7e844
Revises: 9b29edd88996
Create Date: 2022-01-15 01:22:46.123334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c0893c7e844'
down_revision = '9b29edd88996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guild_members_test')
    op.alter_column('reactions', 'reaction',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reactions', 'reaction',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1),
               existing_nullable=False)
    op.create_table('guild_members_test',
    sa.Column('guild_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('nickname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('permissions', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('is_owner', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
