"""empty message

Revision ID: 64c98f6435a0
Revises: d44a89544edc
Create Date: 2022-05-02 18:18:37.312707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c98f6435a0'
down_revision = 'd44a89544edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'access_token',
               existing_type=sa.BIGINT(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('tokens', 'refresh_token',
               existing_type=sa.BIGINT(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'refresh_token',
               existing_type=sa.Text(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('tokens', 'access_token',
               existing_type=sa.Text(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
