"""empty message

Revision ID: 70537b55f4c5
Revises: b89b001de781
Create Date: 2021-12-31 11:16:46.779708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70537b55f4c5'
down_revision = 'b89b001de781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guild_members', 'is_owner',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guild_members', 'is_owner',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
