"""empty message

Revision ID: 850cb8f85c77
Revises: 5c0893c7e844
Create Date: 2022-01-15 01:24:03.993716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850cb8f85c77'
down_revision = '5c0893c7e844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overwrites',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('allow', sa.BigInteger(), nullable=False),
    sa.Column('deny', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'channel_id', 'type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('overwrites')
    # ### end Alembic commands ###
