"""empty message

Revision ID: 85ce80546cd9
Revises: 
Create Date: 2021-11-16 21:00:58.044111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ce80546cd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('channel_members_user_id_fkey', 'channel_members', type_='foreignkey')
    op.drop_constraint('channel_members_channel_id_fkey', 'channel_members', type_='foreignkey')
    op.create_foreign_key(None, 'channel_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'channel_members', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('channels_guild_id_fkey', 'channels', type_='foreignkey')
    op.drop_constraint('channels_owner_id_fkey', 'channels', type_='foreignkey')
    op.drop_constraint('channels_parent_id_fkey', 'channels', type_='foreignkey')
    op.create_foreign_key(None, 'channels', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'channels', 'channels', ['parent_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'channels', 'guilds', ['guild_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('guild_members_user_id_fkey', 'guild_members', type_='foreignkey')
    op.drop_constraint('guild_members_guild_id_fkey', 'guild_members', type_='foreignkey')
    op.create_foreign_key(None, 'guild_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'guild_members', 'guilds', ['guild_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('invites_user_id_fkey', 'invites', type_='foreignkey')
    op.drop_constraint('invites_channel_id_fkey', 'invites', type_='foreignkey')
    op.create_foreign_key(None, 'invites', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'invites', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('messages_author_id_fkey', 'messages', type_='foreignkey')
    op.drop_constraint('messages_replies_to_fkey', 'messages', type_='foreignkey')
    op.drop_constraint('messages_channel_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'messages', ['replies_to'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'messages', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('overwrites_role_id_fkey', 'overwrites', type_='foreignkey')
    op.drop_constraint('overwrites_member_id_fkey', 'overwrites', type_='foreignkey')
    op.drop_constraint('overwrites_channel_id_fkey', 'overwrites', type_='foreignkey')
    op.create_foreign_key(None, 'overwrites', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'overwrites', 'guild_members', ['member_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'overwrites', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.drop_column('overwrites', 'target_id')
    op.drop_constraint('pinned_messages_channel_id_fkey', 'pinned_messages', type_='foreignkey')
    op.drop_constraint('pinned_messages_message_id_fkey', 'pinned_messages', type_='foreignkey')
    op.create_foreign_key(None, 'pinned_messages', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pinned_messages', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('reactions_message_id_fkey', 'reactions', type_='foreignkey')
    op.drop_constraint('reactions_user_id_fkey', 'reactions', type_='foreignkey')
    op.create_foreign_key(None, 'reactions', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('role_members_member_id_fkey', 'role_members', type_='foreignkey')
    op.drop_constraint('role_members_role_id_fkey', 'role_members', type_='foreignkey')
    op.create_foreign_key(None, 'role_members', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'role_members', 'guild_members', ['member_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('roles_guild_id_fkey', 'roles', type_='foreignkey')
    op.create_foreign_key(None, 'roles', 'guilds', ['guild_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.create_foreign_key('roles_guild_id_fkey', 'roles', 'guilds', ['guild_id'], ['id'])
    op.drop_constraint(None, 'role_members', type_='foreignkey')
    op.drop_constraint(None, 'role_members', type_='foreignkey')
    op.create_foreign_key('role_members_role_id_fkey', 'role_members', 'roles', ['role_id'], ['id'])
    op.create_foreign_key('role_members_member_id_fkey', 'role_members', 'guild_members', ['member_id'], ['id'])
    op.drop_constraint(None, 'reactions', type_='foreignkey')
    op.drop_constraint(None, 'reactions', type_='foreignkey')
    op.create_foreign_key('reactions_user_id_fkey', 'reactions', 'users', ['user_id'], ['id'])
    op.create_foreign_key('reactions_message_id_fkey', 'reactions', 'messages', ['message_id'], ['id'])
    op.drop_constraint(None, 'pinned_messages', type_='foreignkey')
    op.drop_constraint(None, 'pinned_messages', type_='foreignkey')
    op.create_foreign_key('pinned_messages_message_id_fkey', 'pinned_messages', 'messages', ['message_id'], ['id'])
    op.create_foreign_key('pinned_messages_channel_id_fkey', 'pinned_messages', 'channels', ['channel_id'], ['id'])
    op.add_column('overwrites', sa.Column('target_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'overwrites', type_='foreignkey')
    op.drop_constraint(None, 'overwrites', type_='foreignkey')
    op.drop_constraint(None, 'overwrites', type_='foreignkey')
    op.create_foreign_key('overwrites_channel_id_fkey', 'overwrites', 'channels', ['channel_id'], ['id'])
    op.create_foreign_key('overwrites_member_id_fkey', 'overwrites', 'guild_members', ['member_id'], ['id'])
    op.create_foreign_key('overwrites_role_id_fkey', 'overwrites', 'roles', ['role_id'], ['id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_channel_id_fkey', 'messages', 'channels', ['channel_id'], ['id'])
    op.create_foreign_key('messages_replies_to_fkey', 'messages', 'messages', ['replies_to'], ['id'])
    op.create_foreign_key('messages_author_id_fkey', 'messages', 'users', ['author_id'], ['id'])
    op.drop_constraint(None, 'invites', type_='foreignkey')
    op.drop_constraint(None, 'invites', type_='foreignkey')
    op.create_foreign_key('invites_channel_id_fkey', 'invites', 'channels', ['channel_id'], ['id'])
    op.create_foreign_key('invites_user_id_fkey', 'invites', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'guild_members', type_='foreignkey')
    op.drop_constraint(None, 'guild_members', type_='foreignkey')
    op.create_foreign_key('guild_members_guild_id_fkey', 'guild_members', 'guilds', ['guild_id'], ['id'])
    op.create_foreign_key('guild_members_user_id_fkey', 'guild_members', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.create_foreign_key('channels_parent_id_fkey', 'channels', 'channels', ['parent_id'], ['id'])
    op.create_foreign_key('channels_owner_id_fkey', 'channels', 'users', ['owner_id'], ['id'])
    op.create_foreign_key('channels_guild_id_fkey', 'channels', 'guilds', ['guild_id'], ['id'])
    op.drop_constraint(None, 'channel_members', type_='foreignkey')
    op.drop_constraint(None, 'channel_members', type_='foreignkey')
    op.create_foreign_key('channel_members_channel_id_fkey', 'channel_members', 'channels', ['channel_id'], ['id'])
    op.create_foreign_key('channel_members_user_id_fkey', 'channel_members', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
