"""empty message

Revision ID: 93ef61092766
Revises: 4290e3aaa29b
Create Date: 2022-05-11 23:50:23.972823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ef61092766'
down_revision = '4290e3aaa29b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emoji',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('roles', sa.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('animated', sa.Boolean(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emoji')
    # ### end Alembic commands ###
