"""empty message

Revision ID: a56c98323426
Revises: b4d5cc2b538e
Create Date: 2022-05-01 15:34:13.737489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a56c98323426'
down_revision = 'b4d5cc2b538e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
