"""empty message

Revision ID: b4d5cc2b538e
Revises: 317ddf3a53c7
Create Date: 2022-04-30 13:57:56.133074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d5cc2b538e'
down_revision = '317ddf3a53c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('messages_webhook_id_fkey', 'messages', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('messages_webhook_id_fkey', 'messages', 'webhooks', ['webhook_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
