"""empty message

Revision ID: b89b001de781
Revises: 54d94892285e
Create Date: 2021-12-23 18:11:34.663340

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b89b001de781'
down_revision = '54d94892285e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_members', sa.Column('is_owner', sa.Boolean(), default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_members', 'is_owner')
    # ### end Alembic commands ###
