"""empty message

Revision ID: c3481a3298d1
Revises: 
Create Date: 2021-11-18 23:37:30.234793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3481a3298d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_bans',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'guild_id'),
    sa.UniqueConstraint('guild_id', 'user_id', name='guild_bans_guild_id_user_id_key')
    )
    op.create_table('thread_metadata',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('archive_timestamp', sa.DateTime(), nullable=True),
    sa.Column('auto_archive_duration', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thread_metadata')
    op.drop_table('guild_bans')
    # ### end Alembic commands ###
