"""empty message

Revision ID: e39a29767b9d
Revises: b7bd3f9264de
Create Date: 2022-05-03 23:44:28.561945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e39a29767b9d'
down_revision = 'b7bd3f9264de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('tag', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'roles', 'users', ['tag'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'tag')
    # ### end Alembic commands ###
