"""empty message

Revision ID: e6a4acc36286
Revises: 0d15c65332c3
Create Date: 2022-05-13 18:46:55.023418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6a4acc36286'
down_revision = '0d15c65332c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reactions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'reactions')
    # ### end Alembic commands ###
