"""empty message

Revision ID: edd72e29be00
Revises: 1ef8e409536c
Create Date: 2022-05-15 22:00:14.727264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edd72e29be00'
down_revision = '1ef8e409536c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relationships', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relationships', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
