"""Messages and Reactions

Revision ID: 3bebbd017b4a
Revises: 860c53774fb8
Create Date: 2021-11-07 20:30:50.369011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3bebbd017b4a'
down_revision = '860c53774fb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('replies_to', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'messages', 'messages', ['replies_to'], ['id'])
    op.drop_column('messages', 'mention_everyone')
    op.drop_column('messages', 'mention_channels')
    op.drop_column('messages', 'mentions')
    op.drop_column('messages', 'mention_roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('mention_roles', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('mentions', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('mention_channels', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('mention_everyone', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'replies_to')
    # ### end Alembic commands ###
