"""Guilds

Revision ID: 6bd32da46085
Revises: e753c46d5648
Create Date: 2021-10-31 12:06:17.965637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bd32da46085'
down_revision = 'e753c46d5648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_members',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('nickname', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('guild_member')
    op.drop_constraint('name_tag_uc', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('name_tag_uc', 'users', ['username', 'tag'])
    op.create_table('guild_member',
    sa.Column('guild_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], name='guild_member_guild_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='guild_member_user_id_fkey')
    )
    op.drop_table('guild_members')
    # ### end Alembic commands ###
