"""Messages and Reactions

Revision ID: 860c53774fb8
Revises: bbd621cf1c80
Create Date: 2021-10-31 23:05:11.505713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '860c53774fb8'
down_revision = 'bbd621cf1c80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('edited_timestamp', sa.DateTime(), nullable=True),
    sa.Column('tts', sa.Boolean(), nullable=False),
    sa.Column('mention_everyone', sa.Boolean(), nullable=False),
    sa.Column('mentions', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('mention_roles', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('mention_channels', sa.ARRAY(sa.BigInteger()), nullable=True),
    sa.Column('embeds', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reaction', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reactions')
    op.drop_table('messages')
    # ### end Alembic commands ###
