"""Invites

Revision ID: b904625eee0b
Revises: baaed050bf01
Create Date: 2021-11-08 13:14:47.968371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b904625eee0b'
down_revision = 'baaed050bf01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('max_age', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invites', 'max_age')
    # ### end Alembic commands ###
