"""Invites

Revision ID: baaed050bf01
Revises: 7f20e3c546d3
Create Date: 2021-11-08 13:10:05.718051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'baaed050bf01'
down_revision = '7f20e3c546d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('invites', sa.Column('max_uses', sa.Integer(), nullable=True))
    op.drop_column('invites', 'expires_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('invites', 'max_uses')
    op.drop_column('invites', 'created_at')
    # ### end Alembic commands ###
