"""Invites

Revision ID: db080c13c102
Revises: b904625eee0b
Create Date: 2021-11-08 17:03:35.984981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db080c13c102'
down_revision = 'b904625eee0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_members', 'id')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['username', 'tag'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.add_column('guild_members', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
