"""Guilds

Revision ID: f65fc1a96699
Revises: afe9d6f0856e
Create Date: 2021-10-31 10:56:15.860170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f65fc1a96699'
down_revision = 'afe9d6f0856e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_member',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_table('guild_members')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_members',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nickname', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('joined_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], name='guild_members_guild_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='guild_members_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='guild_members_pkey')
    )
    op.drop_table('guild_member')
    # ### end Alembic commands ###
