"""User Table

Revision ID: f886fbf22d63
Revises: 60a7a4c9bf6b
Create Date: 2021-10-30 21:08:15.309898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f886fbf22d63'
down_revision = '60a7a4c9bf6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=False))
    op.drop_constraint('users_tag_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_tag_key', 'users', ['tag'])
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
